### ISSUE TITLE
Tor ip will change after every God damn request.

### ISSUE THREAD

**Issue by SingleDevX** [deedy5/requests_tor#13]
Hi, Tor ip will change after every God damn request.

```
ports = []
for id in range(1000):
    ports.append(5000 + id)

rt = RequestsTor(tor_ports=ports, autochange_id=0)
url = 'https://httpbin.org/anything'
first = rt.get(url)
print(first.text)
second = rt.get(url)
print(second.text)
```

**Comment by deedy5** [comment]
Different ports will give different ip. If you want the same ip, send requests through the same port.

**Comment by SingleDevX** [comment]
How can I give range ports to the tor and use it?

**Comment by deedy5** [comment]
show me the code

**Comment by SingleDevX** [comment]
> show me the code

```
ports = []
for id in range(1000):
    ports.append(5000 + id)

rt = RequestsTor(tor_ports=ports, autochange_id=0)
url = 'https://httpbin.org/anything'
first = rt.get(url)
print(first.text)
second = rt.get(url)
print(second.text)
```

**Comment by deedy5** [comment]
Didn't understand the question.
Doesn't it start? Show me the error.

**Comment by SingleDevX** [comment]
can i change 4000 times ip? it changes just 300 IP per hour.

**Comment by deedy5** [comment]
I don't understand the question. 
Why do you need to change ip 4000 times?
Show me your code where the error appears, so I can reproduce the problem.
